# Generated by Django 6.0.1 on 2026-04-20 13:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Glamping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Название Глемпинга, заголовок первого блока",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        verbose_name="продающий текст (hero-секция) под заголовком первого блока"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=100,
                        verbose_name="Короткая “человеческая” геолокация",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        db_index=True,
                        max_length=150,
                        verbose_name="Точный адрес (для карты, юридически и навигации)",
                    ),
                ),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Цена за 1 ночь",
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, verbose_name="Залог"
                    ),
                ),
                (
                    "check_out_time",
                    models.TimeField(
                        default=datetime.time(12, 0), verbose_name="Время выселения"
                    ),
                ),
                (
                    "check_in_time",
                    models.TimeField(
                        default=datetime.time(14, 0), verbose_name="Время заселения"
                    ),
                ),
                (
                    "max_guests",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Параметр задает максимально допустимое кол-во гостей",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Используйте только латиницу, цифры и дефис. Определяет путь к странице.",
                        max_length=100,
                        unique=True,
                        verbose_name="URL (slug) Адресная ссылка",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Введите корректный номер телефона",
                                regex="^\\+?[0-9\\s\\-\\(\\)]{7,20}$",
                            )
                        ],
                        verbose_name="Телефон владельца глемпинга/арендодателя",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email владельца",
                    ),
                ),
            ],
            options={
                "verbose_name": "Glamping",
                "verbose_name_plural": "glampings",
            },
        ),
    ]
