# Generated by Django 6.0.1 on 2026-05-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glamping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="glamping",
            name="extra_guest_price",
            field=models.DecimalField(
                decimal_places=2,
                default=1200,
                max_digits=8,
                verbose_name="Доплата за каждого гостя свыше 2",
            ),
        ),
    ]
