# Generated by Django 6.0.1 on 2026-08-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glamping", "0002_glamping_extra_guest_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="glamping",
            name="single_night_extra_guest_price",
            field=models.DecimalField(
                decimal_places=2,
                default=1500,
                max_digits=8,
                verbose_name="Доплата за каждого гостя свыше 2, при аренде на 1 сутки",
            ),
        ),
        migrations.AddField(
            model_name="glamping",
            name="single_night_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Цена за 1 ночь"
            ),
        ),
        migrations.AlterField(
            model_name="glamping",
            name="price_per_night",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Цена за ночь (от 2 ночей)",
            ),
        ),
    ]
