# Generated by Django 6.0.1 on 2026-06-16 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CinemaBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя клиента")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "movie_name",
                    models.CharField(max_length=200, verbose_name="Название фильма"),
                ),
                ("session_date", models.DateField(verbose_name="Дата сеанса")),
                ("session_time", models.TimeField(verbose_name="Время начала сеанса")),
                (
                    "comments",
                    models.TextField(
                        max_length=2000,
                        validators=[django.core.validators.MinLengthValidator(10)],
                        verbose_name="Пожелания и комментарии",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("confirmed", "Подтвержден"),
                            ("completed", "Выполнен"),
                            ("cancelled", "Отменен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания заказа"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ сеанса кинотеатра",
                "verbose_name_plural": "Заказы сеансов кинотеатра",
                "ordering": ["-created_at"],
            },
        ),
    ]
