# Generated by Django 6.0.1 on 2026-05-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="gallery/static/img", verbose_name="Изображение"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("horizontal", "Горизонтальная"),
                            ("vertical", "Вертикальная"),
                            ("square", "Квадратная"),
                        ],
                        default="horizontal",
                        max_length=20,
                        verbose_name="Ориентация",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография галереи",
                "verbose_name_plural": "Галерея",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
