# Generated by Django 6.0.1 on 2026-05-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(upload_to="gallery/", verbose_name="Изображение"),
        ),
    ]
