# Generated by Django 6.0.1 on 2026-05-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="display_name",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Отображаемое в профиле имя"
            ),
        ),
    ]
