# Generated by Django 6.0.1 on 2026-05-18 13:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        validators=[
                            django.core.validators.MaxLengthValidator(
                                3000,
                                message="Отзыв слишком длинный (максимум 3000 символов)",
                            )
                        ],
                        verbose_name="Текст отзыва",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        help_text="Поставьте оценку от 1 до 5 звезд",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Оценка не может быть ниже 1"
                            ),
                            django.core.validators.MaxValueValidator(
                                5, message="Оценка не может быть выше 5"
                            ),
                        ],
                        verbose_name="Рейтинг-оценка, от 1 до 5",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания отзыва!"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор отзыва",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
