        listen 443 ssl;
        server_name kama-glamping.ru www.kama-glamping.ru;

        ssl_certificate /etc/letsencrypt/live/kama-glamping.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/kama-glamping.ru/privkey.pem;

        client_max_body_size 20M;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        location /static/ {
            alias /app/staticfiles/;
            expires 30d;
            add_header Cache-Control "public, immutable";
        }

        location /media/ {
            alias /app/media/;
            expires 7d;
            add_header Cache-Control "public";
        }

        location / {
            proxy_pass http://django;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_redirect off;
        }
    }
}

